import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

/**
 * Created by ::  llama ::  3/20/16.
 * For :: WeinFilder
 */
public class Axis extends JFrame {

    public Axis(String input) {
        super(input);

        setContentPane(Axis);

        pack();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);


        setVisible(true);
        slider1.addComponentListener(new ComponentAdapter() {
        });
        exactCheckBox.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent propertyChangeEvent) {

            }
        });
    }

    private JSlider slider1;
    private JCheckBox exactCheckBox;
    private JTextField valueValue;
    private JPanel Axis;

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    public void setData(Axis data) {
    }

    public void getData(Axis data) {
    }

    public boolean isModified(Axis data) {
        return false;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Axis = new JPanel();
        Axis.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        label1.setText("Axis");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        Axis.add(label1, gbc);
        slider1 = new JSlider();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Axis.add(slider1, gbc);
        exactCheckBox = new JCheckBox();
        exactCheckBox.setText("Exact");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        Axis.add(exactCheckBox, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Value");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        Axis.add(label2, gbc);
        valueValue = new JTextField();
        valueValue.setHorizontalAlignment(0);
        valueValue.putClientProperty("html.disable", Boolean.TRUE);
        valueValue.putClientProperty("caretWidth", new Integer(10));
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 0, 100);
        Axis.add(valueValue, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Axis;
    }
}
